/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVendasRouteImport } from './routes/_authenticated/vendas'
import { Route as AuthenticatedReservasRouteImport } from './routes/_authenticated/reservas'
import { Route as AuthenticatedReclamacoesRouteImport } from './routes/_authenticated/reclamacoes'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedMapaRouteImport } from './routes/_authenticated/mapa'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedAvaliacoesRouteImport } from './routes/_authenticated/avaliacoes'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVendasRoute = AuthenticatedVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReservasRoute = AuthenticatedReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReclamacoesRoute =
  AuthenticatedReclamacoesRouteImport.update({
    id: '/reclamacoes',
    path: '/reclamacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapaRoute = AuthenticatedMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAvaliacoesRoute = AuthenticatedAvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/avaliacoes': typeof AuthenticatedAvaliacoesRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/reclamacoes': typeof AuthenticatedReclamacoesRoute
  '/reservas': typeof AuthenticatedReservasRoute
  '/vendas': typeof AuthenticatedVendasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/avaliacoes': typeof AuthenticatedAvaliacoesRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/reclamacoes': typeof AuthenticatedReclamacoesRoute
  '/reservas': typeof AuthenticatedReservasRoute
  '/vendas': typeof AuthenticatedVendasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/avaliacoes': typeof AuthenticatedAvaliacoesRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/mapa': typeof AuthenticatedMapaRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/reclamacoes': typeof AuthenticatedReclamacoesRoute
  '/_authenticated/reservas': typeof AuthenticatedReservasRoute
  '/_authenticated/vendas': typeof AuthenticatedVendasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/avaliacoes'
    | '/clientes'
    | '/mapa'
    | '/painel'
    | '/reclamacoes'
    | '/reservas'
    | '/vendas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/avaliacoes'
    | '/clientes'
    | '/mapa'
    | '/painel'
    | '/reclamacoes'
    | '/reservas'
    | '/vendas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/avaliacoes'
    | '/_authenticated/clientes'
    | '/_authenticated/mapa'
    | '/_authenticated/painel'
    | '/_authenticated/reclamacoes'
    | '/_authenticated/reservas'
    | '/_authenticated/vendas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vendas': {
      id: '/_authenticated/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof AuthenticatedVendasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reservas': {
      id: '/_authenticated/reservas'
      path: '/reservas'
      fullPath: '/reservas'
      preLoaderRoute: typeof AuthenticatedReservasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reclamacoes': {
      id: '/_authenticated/reclamacoes'
      path: '/reclamacoes'
      fullPath: '/reclamacoes'
      preLoaderRoute: typeof AuthenticatedReclamacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mapa': {
      id: '/_authenticated/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof AuthenticatedMapaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/avaliacoes': {
      id: '/_authenticated/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/avaliacoes'
      preLoaderRoute: typeof AuthenticatedAvaliacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAvaliacoesRoute: typeof AuthenticatedAvaliacoesRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedMapaRoute: typeof AuthenticatedMapaRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedReclamacoesRoute: typeof AuthenticatedReclamacoesRoute
  AuthenticatedReservasRoute: typeof AuthenticatedReservasRoute
  AuthenticatedVendasRoute: typeof AuthenticatedVendasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAvaliacoesRoute: AuthenticatedAvaliacoesRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedMapaRoute: AuthenticatedMapaRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedReclamacoesRoute: AuthenticatedReclamacoesRoute,
  AuthenticatedReservasRoute: AuthenticatedReservasRoute,
  AuthenticatedVendasRoute: AuthenticatedVendasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
